name: visual-test-delete
on:
  delete:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: delete visual test
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          DELETE_BRANCH: captures/${{ github.ref }}
        run: |
          env
          # git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
          # git push --delete origin captures/${GITHUB_REF}
