name: visual-test-pr
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: xbrowser-yarn-${{ hashFiles('**\yarn.lock') }}
          restore-keys: xbrowser-yarn-
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn
      - name: Build test
        run: |
          # yarn build
      - name: Screnn capture
        run: yarn sc:capture
      - name: reg
        run: |
          mkdir __reg__
          mv __screenshots__ __reg__/actual/
          git clone https://github.com/SoraKumo001/visual-test -b captures/refs/heads/master __reg2__/expected
          cp -Rf __reg2__/expected/* __reg__/expected
          yarn reg-cli  __reg__/actual  __reg__/expected __reg__/diff -R __reg__/index.html -J __reg__/reg.json -I
          cp -Rf __reg2__/expected/* __reg__/expected
      - name: Save reg
        uses: peaceiris/actions-gh-pages@v2.4.0
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: regs/${{ github.ref }}
          PUBLISH_DIR: ./__reg__
